"use client";
import { useState } from "react";

type Toast = { kind: "ok" | "warn"; msg: string } | null;

const URL_LIMIT = 1500; // browsers happily accept more, but some shells truncate

async function copy(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

function openTab(url: string) {
  const w = window.open(url, "_blank", "noopener,noreferrer");
  if (w) w.opener = null;
}

async function downloadPptx(text: string, title: string) {
  const PptxGenJS = (await import("pptxgenjs")).default;
  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE"; // 13.33 × 7.5"
  const slide = pptx.addSlide();
  slide.background = { color: "FAFAF9" };
  slide.addText(title, {
    x: 0.6,
    y: 0.45,
    w: 12.1,
    h: 0.7,
    fontSize: 26,
    bold: true,
    color: "1C1917",
    fontFace: "Helvetica",
  });
  slide.addText(text, {
    x: 0.6,
    y: 1.3,
    w: 12.1,
    h: 5.8,
    fontSize: 14,
    color: "1C1917",
    valign: "top",
    fontFace: "Helvetica",
    paraSpaceAfter: 6,
  });
  slide.addText("Generated by chAIn — privacy gateway", {
    x: 0.6,
    y: 7.05,
    w: 12.1,
    h: 0.3,
    fontSize: 10,
    color: "78716C",
    fontFace: "Helvetica",
    italic: true,
  });
  await pptx.writeFile({ fileName: "chain-anonymized.pptx" });
}

export function OutboundChannels({ text }: { text: string }) {
  const [toast, setToast] = useState<Toast>(null);
  const [busy, setBusy] = useState<string | null>(null);

  function flash(t: Toast, ms = 2400) {
    setToast(t);
    setTimeout(() => setToast(null), ms);
  }

  async function copyOnly() {
    const ok = await copy(text);
    flash(ok ? { kind: "ok", msg: "Copied" } : { kind: "warn", msg: "Copy failed" });
  }

  async function openIn(label: string, urlBuilder: (q: string) => string) {
    const ok = await copy(text);
    const trimmed = text.length > URL_LIMIT ? text.slice(0, URL_LIMIT) : text;
    openTab(urlBuilder(trimmed));
    flash(
      ok
        ? {
            kind: "ok",
            msg:
              text.length > URL_LIMIT
                ? `${label} opened — text was long, paste with Cmd-V`
                : `${label} opened`,
          }
        : { kind: "warn", msg: `${label} opened — copy to clipboard failed` },
    );
  }

  async function pptx() {
    setBusy("pptx");
    try {
      await downloadPptx(text, "chAIn — anonymized output");
      flash({ kind: "ok", msg: "Slide deck downloaded" });
    } catch (e) {
      flash({ kind: "warn", msg: `Slide export failed: ${e instanceof Error ? e.message : "unknown"}` });
    } finally {
      setBusy(null);
    }
  }

  return (
    <div className="flex flex-wrap items-center gap-2">
      <Btn onClick={copyOnly}>Copy</Btn>
      <Btn
        onClick={() =>
          openIn("ChatGPT", (q) => `https://chatgpt.com/?q=${encodeURIComponent(q)}`)
        }
      >
        Open in ChatGPT
      </Btn>
      <Btn
        onClick={() =>
          openIn("Claude", (q) => `https://claude.ai/new?q=${encodeURIComponent(q)}`)
        }
      >
        Open in Claude
      </Btn>
      <Btn onClick={pptx} disabled={busy === "pptx"}>
        {busy === "pptx" ? "Building…" : "Download as .pptx"}
      </Btn>

      {toast && (
        <span
          className={`ml-1 rounded px-2 py-0.5 text-[11px] ${
            toast.kind === "ok"
              ? "bg-[var(--sev-safe-bg)] text-[var(--sev-safe)]"
              : "bg-[var(--sev-review-bg)] text-[var(--sev-review)]"
          }`}
        >
          {toast.msg}
        </span>
      )}
    </div>
  );
}

function Btn({
  onClick,
  disabled,
  children,
}: {
  onClick: () => void;
  disabled?: boolean;
  children: React.ReactNode;
}) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className="rounded border px-3 py-1 text-xs hover:bg-[var(--line)]/40 disabled:opacity-50"
    >
      {children}
    </button>
  );
}
